name: Feature Request
description: Request a new feature for dsigma.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please let us know what feature you would like to see in ``dsigma`` and why.
      required: true
